import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  Header  from "@/components/layout/Header";
import  Claudai from "@/components/home/Claudai";
import  Theworld from "@/components/home/Theworld";
import  PlatformSuite from "@/components/home/PlatformSuite";
import  Corepiller from "@/components/home/Corepiller";
import  SolutionsSection from "@/components/home/SolutionsSection";
import  Industry from "@/components/home/Industry";
import  Partners from "@/components/home/Partners";
import  LearningCenter from "@/components/home/LearningCenter";
import  Leading from "@/components/home/Leading";
import  Ready from "@/components/home/Ready";
import  Footer  from "@/components/layout/Footer";
// import { Aktiv_Grotesk } from "https://use.typekit.net/lrf5trx.css";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <Header/>
        {/* <Claudai/> */}
        <Theworld/>
        <PlatformSuite/>
        <Corepiller/>
        <SolutionsSection/>
        <Industry/>
        <Partners/>
        <LearningCenter/>
        <Leading/>
        <Ready/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
